#!/bin/zsh
# vphone-tier: build
# setup_tools.sh — the one development tool that is not in this repository.
#
# There is nothing to install any more. This script used to run `brew install`
# for six packages and build two tools from submodules; all of it is gone except
# insert_dylib, which no shipped code runs and which exists only so a test has
# something independent to compare against.
#
#   aria2 wget       download fallbacks in fw_prepare.sh -> curl, which is macOS
#   gnu-tar zstd     -> vphone-archive
#   ldid-procursus   -> `vphone-cli sign`
#   openssl@3        only ever linked into the trustcache build below
#   sshpass          installed for years and invoked by nothing in this repo
#   trustcache       built, bundled into the .app, and invoked by nothing. The
#                    trust cache is generated by cryptexctl out of
#                    /System/Library/SecurityResearch. It was also the last file
#                    in the bundle linking /opt/homebrew's libcrypto.3.
#
# So: no Homebrew, no interpreter, no environment. `scripts/build.sh` builds the app.
#
# Run: zsh scripts/setup_tools.sh before the optional byte-parity test.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLS_PREFIX="${TOOLS_PREFIX:-$PROJECT_DIR/.tools}"
REPOS_DIR="$SCRIPT_DIR/repos"

ensure_repo_submodule() {
    local rel_path="$1"
    local abs_path="$PROJECT_DIR/$rel_path"

    if [[ ! -e "$abs_path/.git" ]]; then
        git -C "$PROJECT_DIR" submodule update --init --recursive "$rel_path"
    fi
}

# ── insert_dylib (test reference only) ─────────────────────────
#
# Nothing in the product runs this: `CFWInjectDylib` injects the weak load
# command in-process, and the last caller that shelled out was
# scripts/patchers/cfw.py. It is still built because it is the independent
# reference CFWMachOTests.matchesInsertDylib compares the Swift injector
# against, byte for byte — that test skips silently when it is missing, which
# is the worst possible way to lose the check.
#
# It is one .c file and one system framework, so this needs clang and nothing
# else. There is no `brew install` left in this script.

echo "insert_dylib (byte-parity reference for CFWMachOTests)"

INSERT_DYLIB_BIN="$TOOLS_PREFIX/bin/insert_dylib"
if [[ -x "$INSERT_DYLIB_BIN" ]]; then
    echo "  Already built: $INSERT_DYLIB_BIN"
else
    INSERT_DYLIB_DIR="$REPOS_DIR/insert_dylib"
    ensure_repo_submodule "scripts/repos/insert_dylib"
    echo "  Building insert_dylib..."
    mkdir -p "$TOOLS_PREFIX/bin"
    clang -o "$INSERT_DYLIB_BIN" "$INSERT_DYLIB_DIR/insert_dylib/main.c" -framework Security -O2
    echo "  Installed: $INSERT_DYLIB_BIN"
fi

echo ""
echo "All tools installed."
